---
title: "From metawebs to regional and local"
author: "L.A.S. - T. M."
output: html_document
---

## Setup

```{r setup, eval=T,echo=FALSE }
load(".RData")
#simul  <- F # variable to perform or not the simulations


oldcd <-getwd()


# require(pander)
# require(plyr)
# require(dplyr)
# panderOptions('table.split.table',Inf)
# panderOptions('table.style', 'multiline')
# options("scipen"=6, "digits"=4)
# 
# #Load package
# library(poweRlaw) 
# source("R/dist_fun.r")
# # 
# # Load functions for discrete distributions
# # # 
# # Load functions for continuous ht distributions
# # 
# 
# source("R/powerlaw/discpowerexp.R")
# source("R/powerlaw/discexp.R")
# source("R/powerlaw/zeta.R")
# # 
# # Load functions for continuous ht distributions
# # 
# source("R/powerlaw/powerexp.R")
# source("R/powerlaw/exp.R")
# source("R/powerlaw/pareto.R")
# #

```


# Modularity Analysis - Local  

```{r ModularityAnalysisLocal, eval=T,echo=F,message=T,warning=T}

source("R/network_fun.r")

require(igraph)
require(dplyr)
require(stringr)

#
# Read data and trim species names to avoid duplicates 
#
dtot <- read.delim("Data/Foodwebs.dat", quote="",stringsAsFactors = F)
dtot <- dtot %>% mutate(Predator_name=str_trim(Predator_name), Prey_name=str_trim(Prey_name))

#
# Select local food web - Potter Cove
#
dtot1 <- as.matrix(dtot %>% filter(Network=="Local") %>% dplyr::select(Prey_name,Predator_name))
redl <- graph_from_edgelist(dtot1, directed  = T)

#
# Make short names 
#
require(vegan)
spnames <- make.cepnames(V(redl)$name)
#write.csv(V(redl)$name,"Local.csv")

# Test if there are duplicated species
#
V(redl)$name[grep(".1",spnames)]


#
# Run modularity 
#
set.seed(123)
modulos<-cluster_spinglass(redl)
websTbl <- calc_topological_indices(redl)  %>% mutate(Network="Local",Groups=length(modulos$csize),Modularity=modulos$modularity)

#
# Add the modulos object to a vector  
#
mod_by_red <- vector(mode="list", length=3)
mod_by_red[[1]] <- modulos

#
# Compare with random networks
#
tbl <- data.frame()
tbl <- calc_modularity_random(redl,1000)
#saveRDS(tbl,"tbl.rds")
#tbl <- readRDS("tbl.rds")
websTbl <- websTbl %>% bind_cols(tbl)

# Check for detritos
# 
grep("detr", V(redl)$name, ignore.case = TRUE, value=TRUE  )
grep("necr", V(redl)$name, ignore.case = TRUE, value=TRUE  )

#
# Calculate Trophic Position
#
require(NetIndices)
troph.net2<-TrophInd(get.adjacency(redl,sparse=F),Dead=c("Fresh detritus","Aged detritus","Necromass"))
layout.matrix.1<-matrix(
  nrow=length(V(redl)),  # Rows equal to the number of vertices
  ncol=2
)


#
# Calc incoherence
#
q <- calc_incoherence(redl,troph.net2)
websTbl$Q[1] <- q

# Plot the red
# 
# Add colors to nodes 
#
require(RColorBrewer)

colTL <-as.numeric(cut(troph.net2$TL,11))
colnet <- brewer.pal(11,"RdYlGn")
V(redl)$color <- colnet[12-colTL]

#
# Plot modules
#
layout.matrix.1[,2]<-jitter(troph.net2$TL,0.4) # y-axis value based on trophic level
layout.matrix.1[,1]<-jitter(modulos$membership,1) # randomly assign along x-axis

png("Figures/LocalFoodWeb.png",width=6,height=6,units="in",res=600)
par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0))

plot(redl, vertex.color=vertex_attr(redl)$cor,vertex.label=NA,
     vertex.size=log(3*igraph::degree(redl)),
     edge.width=.3,edge.arrow.size=.4, 
     edge.color="grey50",
     edge.curved=0.3, layout=layout.matrix.1)

dev.off()
save.image()
```

# Modularity Analysis - Regional

```{r ModularityAnalysisRegional, eval=T,echo=F,message=T,warning=T}

source("R/network_fun.r")

require(igraph)
require(dplyr)
require(stringr)

#
# Read data and trim species names to avoid duplicates 
#
dtot <- read.delim("Data/Foodwebs.dat", quote="",stringsAsFactors = F)
dtot <- dtot %>% mutate(Predator_name=str_trim(Predator_name), Prey_name=str_trim(Prey_name))

#
# Select food web 
#
dtot1 <- as.matrix(dtot %>% filter(Network=="Regional") %>% dplyr::select(Prey_name,Predator_name))
redl <- graph_from_edgelist(dtot1, directed  = T)
redl <- simplify(redl)

#
# Make short names 
#
require(vegan)
spnames <- make.cepnames(V(redl)$name)
#write.csv(V(redl)$name,"Regional.csv")

# Test if there are duplicated species
#
V(redl)$name[grep(".1",spnames)]

V(redl)$name[which_loop(redl)]

#
# Run modularity 
#
set.seed(123)
modulos<-cluster_spinglass(redl)
websTbl1 <- calc_topological_indices(redl)  %>% mutate(Network="Regional",Groups=length(modulos$csize),Modularity=modulos$modularity)

#
# Add the modulos object to a vector  
#
mod_by_red[[2]] <- modulos

#
# Compare with random networks
#
tbl <- data.frame()
tbl <- calc_modularity_random(redl,1000)
#saveRDS(tbl,"tbl.rds")
#tbl <- readRDS("tbl.rds")
websTbl1 <- websTbl1 %>% bind_cols(tbl)
websTbl <- bind_rows(websTbl,websTbl1)

rm(websTbl1)

# Check for detritos
# 
grep("detr", V(redl)$name, ignore.case = TRUE, value=TRUE  )
grep("necr", V(redl)$name, ignore.case = TRUE, value=TRUE  )

#
# Calculate Trophic Position
#
require(NetIndices)
troph.net2<-TrophInd(get.adjacency(redl,sparse=F),Dead=c("Detritus","Necromass"))
layout.matrix.1<-matrix(
  nrow=length(V(redl)),  # Rows equal to the number of vertices
  ncol=2
)

#
# Calc incoherence
#
q <- calc_incoherence(redl,troph.net2)
websTbl$Q[2] <- q


# 
# Add colors to nodes 
#
require(RColorBrewer)

colTL <-as.numeric(cut(troph.net2$TL,11))
colnet <- brewer.pal(11,"RdYlGn")
V(redl)$color <- colnet[12-colTL]

#
# Plot modules
#
layout.matrix.1[,2]<-jitter(troph.net2$TL,0.4) # y-axis value based on trophic level
layout.matrix.1[,1]<-jitter(modulos$membership,1) # randomly assign along x-axis

png("Figures/RegionalFoodWeb.png",width=6,height=6,units="in",res=600)
par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0))

plot(redl, vertex.color=vertex_attr(redl)$cor,vertex.label=NA,
     vertex.size=log(3*igraph::degree(redl)),
     edge.width=.3,edge.arrow.size=.4, 
     edge.color="grey50",
     edge.curved=0.3, layout=layout.matrix.1)

dev.off()
save.image()

```


# Modularity Analysis - MetaWEB!

```{r ModularityAnalysisMetaWeb, eval=T,echo=F,message=T,warning=T}

source("R/network_fun.r")

require(igraph)
require(dplyr)
require(stringr)

#
# Read data and trim species names to avoid duplicates 
#
dtot <- read.delim("Data/Foodwebs.dat", quote="",stringsAsFactors = F)
dtot <- dtot %>% mutate(Predator_name=str_trim(Predator_name), Prey_name=str_trim(Prey_name))

#
# Select food web 
#
dtot1 <- as.matrix(dtot %>% filter(Network=="Meta") %>% dplyr::select(Prey_name,Predator_name))
redl <- graph_from_edgelist(dtot1, directed  = T)

# Select only a connected subgraph graph 
V(redl)$comp <- components(redl)$membership
redm <- induced_subgraph(redl,V(redl)$comp==1)

# Unconnected components 
redd <- induced_subgraph(redl,V(redl)$comp==2)

# Delete cannibalistic 
redl <- simplify(redm)

#
# Make short names 
#
require(vegan)
spnames <- make.cepnames(V(redl)$name)
#write.csv(V(redl)$name,"Meta.csv")


# Test if there are duplicated species
#
V(redl)$name[grep(".1",spnames)]

#
# Run modularity 
#
set.seed(123)
modulos<-cluster_spinglass(redl)
websTbl1 <- calc_topological_indices(redl)  %>% mutate(Network="Meta",Groups=length(modulos$csize),Modularity=modulos$modularity)

#
# Add the modulos object to a vector  
#
mod_by_red[[3]] <- modulos

# Print species by module
#
# for( i in 1:length(modulos$csize)){
#   if(modulos$csize[i]<10){
#     cat("Group",i, "\n")
#     print(degree(redl,V(redl)[modulos$membership==i]))
#   }
# }

#
# Compare with random networks
#
tbl <- data.frame()
tbl <- calc_modularity_random(redl,1000)
#saveRDS(tbl,"tbl.rds")
#tbl <- readRDS("tbl.rds")
websTbl1 <- websTbl1 %>% bind_cols(tbl)

websTbl <- bind_rows(websTbl,websTbl1)

rm(websTbl1)


#
# Calculate Trophic Position
#
V(redl)$name[grep("Detritus",spnames)]
V(redl)[V(redl)$name=="Necromass"]

require(NetIndices)
troph.net2<-TrophInd(get.adjacency(redl,sparse=F),Dead=c("Detritus","Necromass"))
layout.matrix.1<-matrix(
  nrow=length(V(redl)),  # Rows equal to the number of vertices
  ncol=2
)

#
# Calc incoherence
#
q <- calc_incoherence(redl,troph.net2)
websTbl$Q[3] <- q
# 
# Add colors to nodes 
#
require(RColorBrewer)

colTL <-as.numeric(cut(troph.net2$TL,11))
colnet <- brewer.pal(11,"RdYlGn")
V(redl)$color <- colnet[12-colTL]

#
# Plot modules
#
layout.matrix.1[,2]<-jitter(troph.net2$TL,0.4) # y-axis value based on trophic level
layout.matrix.1[,1]<-jitter(modulos$membership,1) # randomly assign along x-axis

png("Figures/MetaFoodWeb.png",width=6,height=6,units="in",res=600)
par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0))

plot(redl, vertex.color=vertex_attr(redl)$cor,vertex.label=NA,
     vertex.size=log(3*igraph::degree(redl)),
     edge.width=.3,edge.arrow.size=.4, 
     edge.color="grey50",
     edge.curved=0.3, layout=layout.matrix.1)

dev.off()

save.image()

#
# Calculate z-score of modularity
#
websTbl <- websTbl %>% mutate(zMO= (Modularity- rndMO)/(MOhigh-MOlow)*2, zGR=(Groups-rndGR)/(GRhigh-GRlow)*2)


require(pander)
panderOptions('table.split.table',Inf)
panderOptions('table.style', 'multiline')

pandoc.table(t(websTbl %>% dplyr::select(Network,Size,Links,Connectance,PathLength,Clustering,Modularity,Groups,SWness,SWnessCI,zMO,zGR) %>% mutate_if(is.numeric, round, digits=4)))


```

# Analysis of motif - Local

```{r motifAnalysisLocal, eval=T,echo=F,message=T,warning=T}

source("R/network_fun.r")

require(igraph)
require(dplyr)
require(stringr)

#
# Read data and trim species names to avoid duplicates 
#
dtot <- read.delim("Data/Foodwebs.dat", quote="",stringsAsFactors = F)
dtot <- dtot %>% mutate(Predator_name=str_trim(Predator_name), Prey_name=str_trim(Prey_name))

#
# Select local food web - Potter Cove
#
dtot1 <- as.matrix(dtot %>% filter(Network=="Local") %>% dplyr::select(Prey_name,Predator_name))
redl <- graph_from_edgelist(dtot1, directed  = T)

#
# Make short names 
#
require(vegan)
spnames <- make.cepnames(V(redl)$name)
#write.csv(V(redl)$name,"Local.csv")

# Test if there are duplicated species
#
V(redl)$name[grep(".1",spnames)]

#
# Motif
#
mot <- triad_census(redl)

mot[4] # Exploitative competition
mot[5] # Apparent competition
mot[6] # Tri-trophic chain
mot[9] # Omnivory

FreqMotif <- data.frame(Network="Local",t(mot))

set.seed(123)
motif <- calc_motif_random(redl)
motif <- motif %>% mutate(Network="Local")

save.image()
```

# Analysis of motif - Regional

```{r motifAnalysisRegional, eval=T,echo=F,message=T,warning=T}

source("R/network_fun.r")

require(igraph)
require(dplyr)
require(stringr)

#
# Read data and trim species names to avoid duplicates 
#
dtot <- read.delim("Data/Foodwebs.dat", quote="",stringsAsFactors = F)
dtot <- dtot %>% mutate(Predator_name=str_trim(Predator_name), Prey_name=str_trim(Prey_name))

#
# Select food web 
#
dtot1 <- as.matrix(dtot %>% filter(Network=="Regional") %>% dplyr::select(Prey_name,Predator_name))
redl <- graph_from_edgelist(dtot1, directed  = T)
redl <- simplify(redl)

#
# Make short names 
#
require(vegan)
spnames <- make.cepnames(V(redl)$name)
#write.csv(V(redl)$name,"Regional.csv")

# Test if there are duplicated species
#
V(redl)$name[grep(".1",spnames)]
dup <- str_sub(spnames[grep(".1",spnames)], start = 1, end = -3)
V(redl)$name[str_detect(spnames,dup[1])]
V(redl)$name[str_detect(spnames,dup[2])]
V(redl)$name[str_detect(spnames,dup[3])]

V(redl)$name[which_loop(redl)]


#
# Motif
#
mot <- triad_census(redl)
mot[4] # Exploitative competition
mot[5] # Apparent competition
mot[6] # Tri-trophic chain
mot[9] # Omnivory


FreqMotif <- rbind(FreqMotif,data.frame(Network="Regional",t(mot)))

mot[10] # Loop 

set.seed(123)
motif <- bind_rows(motif, calc_motif_random(redl) %>% mutate(Network="Regional"))

save.image()
```


# Motif Analysis - MetaWEB!

```{r MotifAnalysisMetaWeb, eval=T,echo=F,message=T,warning=T}

source("R/network_fun.r")

require(igraph)
require(dplyr)
require(stringr)

#
# Read data and trim species names to avoid duplicates 
#
dtot <- read.delim("Data/Foodwebs.dat", quote="",stringsAsFactors = F)
dtot <- dtot %>% mutate(Predator_name=str_trim(Predator_name), Prey_name=str_trim(Prey_name))

#
# Select food web 
#
dtot1 <- as.matrix(dtot %>% filter(Network=="Meta") %>% dplyr::select(Prey_name,Predator_name))
redl <- graph_from_edgelist(dtot1, directed  = T)

# Select only a connected subgraph graph 
V(redl)$comp <- components(redl)$membership
redm <- induced_subgraph(redl,V(redl)$comp==1)

# Unconnected components 
redd <- induced_subgraph(redl,V(redl)$comp==2)

# Delete cannibalistic 
redl <- simplify(redm)

#
# Make short names 
#
require(vegan)
spnames <- make.cepnames(V(redl)$name)
#write.csv(V(redl)$name,"Meta.csv")


# Test if there are duplicated species
#
V(redl)$name[grep(".1",spnames)]
dup <- str_sub(spnames[grep(".1",spnames)], start = 1, end = -3)
for( i in 1:length(dup)){
  print(V(redl)$name[str_detect(spnames,dup[i])])
}

V(redl)$name[which_loop(redl)]


#
# Motif
#
mot <- triad_census(redl)
mot[4] # Exploitative competition
mot[5] # Apparent competition
mot[6] # Tri-trophic chain
mot[9] # Omnivory

FreqMotif <- rbind(FreqMotif,data.frame(Network="Meta",t(mot)))

mot[10] # Loop 

set.seed(123)
motif <- bind_rows(motif, calc_motif_random(redl) %>% mutate(Network="Meta"))

save.image()

require(pander)
panderOptions('table.split.table',Inf)
panderOptions('table.style', 'multiline')

motif <- motif %>% dplyr::select(Network, 1:length(names(motif)))

pandoc.table(t(motif %>% mutate_if(is.numeric, round, digits=4)))

```

# Analisis of motif frequency change across networks

Pag 616 The R book

```{r MotifAnalysisMetaWeb, eval=T,echo=F,message=T,warning=T}
require(dplyr)
#
# Build a dataframe with the relevant motifs
# 
pFM<- FreqMotif %>% group_by(Network) %>% dplyr::select(X4:X6,X9) %>% rename(EC=X4,AC=X5,TT=X6,OM=X9) %>% mutate(Tot=sum(EC,AC,TT,OM)) %>% ungroup()

require(tidyr)

pFM <- pFM %>% select(Network:OM) %>%gather(motif,count,EC:OM)

#
# Test it using poisson glm (only the interaction counts )
#
model1 <- glm(count~Network*motif,poisson, data=pFM)
summary(model1)
model2 <- glm(count~Network+motif,poisson, data=pFM)

anova(model1,model2,test="Chi")

#
# Pearson Chi-squared independence 
#

x <- FreqMotif %>% dplyr::select(X4:X6,X9) %>% rename(EC=X4,AC=X5,TT=X6,OM=X9)
x <- as.matrix(x)
rownames(x) <- FreqMotif$Network
require(RColorBrewer)
colnet <- brewer.pal(11,"RdYlGn")[c(1,11)]
png("Figures/NetworkByMotifFreq.png",width=6,height=6,units="in",res=600)
par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(2, 2, 0, 2))
colnames(x) <- c("Exploitative\ncompetition", "Apparent\ncompetition", "Tri-trophic\nchain","Omnivory")
assocplot(t(x),col=colnet)
dev.off()
#require(vcd)
#assoc(x, main = "Relation Network and motif", shade = TRUE)

chisq.test(x)

```
 