# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

neutralNetAssembly <- function(rho, m, q, a, time, BB = 0L) {
    .Call(`_MetaWebAssemblyModels_neutralNetAssembly`, rho, m, q, a, time, BB)
}

#'               and the adjacency matrix A. 
cascadeNetAssembly <- function(rho, m, q, a, time, BB = 0L) {
    .Call(`_MetaWebAssemblyModels_cascadeNetAssembly`, rho, m, q, a, time, BB)
}

#'               and the adjacency matrix A. 
metaWebNetAssembly <- function(metaW, m, q, a, time) {
    .Call(`_MetaWebAssemblyModels_metaWebNetAssembly`, metaW, m, q, a, time)
}

